name: Run on Zinal

on:
  push:
    branches:
      - 'fc-*'

jobs:
  build:
    runs-on: zinal
    steps:
      - name: Setup temporary dir
        run: |
          TMP_DIR=$(mktemp -d)
          echo "TMP_DIR=$TMP_DIR" >> $GITHUB_ENV
          echo "Using temp directory: $TMP_DIR" 

      - name: Manually clone repo within tmp dir
        run: git clone --depth 1 --branch "${GITHUB_REF_NAME}" https://github.com/${GITHUB_REPOSITORY}.git
        working-directory: ${{ env.TMP_DIR }}

      - name: List contents of TMP_DIR
        run: ls -la
        working-directory: ${{ env.TMP_DIR }}

      - name: Run build inside Podman container
        run: |
          podman run --rm \
          -v "$PWD":"$PWD":Z \
          -v "$TMP_DIR":"$TMP_DIR":Z \
          -w "$PWD" \
          ghcr.io/sarus-suite/parallax/ci-runner:latest \
          bash -c "
            set -eux
            mkdir -p $TMP_DIR/dist
            ls
            go version
            VER=opensuse-15.5
            HOST_ARCH=\$(go env GOHOSTARCH)
            OUT=parallax-${GITHUB_REF_NAME}-${VER}-${HOST_ARCH}
            echo Building \$OUT
            go get .
            "
        working-directory: ${{ env.TMP_DIR }}/parallax



          #      - name: Build parallax
          #        env:
          #          CGO_ENABLED: "1"
          #          CC: gcc
          #          GOOS: linux
          #          GOFLAGS: "-buildvcs=false"
          #          GO_LDFLAGS: "-linkmode external"
          #          CGO_LDFLAGS: "-g -O2"
          #          CGO_CFLAGS: "-I/users/felipecr/btrfs-progs/include"
          #        run: |
          #          VER="opensuse-$(lsb_release -rs)"
          #          mkdir -p dist
          #          HOST_ARCH=$(go env GOHOSTARCH)
          #          OUT="parallax-${{ github.ref_name }}-${VER}-${HOST_ARCH}"
          #          echo "Building $OUT"
          #          GOARCH=$HOST_ARCH go build -v -x \
          #          -ldflags "-X 'github.com/sarus-suite/parallax/version.Version=${{ github.ref_name }}'" \
          #          -o dist/$OUT \
          #          .

      - name: Run a script
        run: |
          echo "Hello from zinal runner!"
          uname -a

