name: Run on Zinal

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: zinal
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a script
        run: |
          echo "Hello from zinal runner!"
          uname -a

